project:
  type: website

website:
  title: "EcoAssets"
  open-graph: true 
  page-footer: 
    right: "Copyright 2024"
    background: "#02055Dff"
    foreground: "#FFFFFF"
  navbar:
    background: "#1a4111ff"
    foreground: "#FFFFFF"
    collapse: true
    pinned: false
    back-to-top-navigation: true
    search: true
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
        aria-label: "Homepage"
      - href: about.qmd
        text: "About"
      - text: "Data"
        menu: 
          - data.qmd
          - biodiversity_data.qmd
          - monitoring_data.qmd
      - href: news.qmd
        text: "News"
      - text: Stories
        menu:
          - href: stories/dataStory0.qmd
            text: "A simple data story"
          - href: stories/d3Chart.qmd
            text: "d3 and JS experiments"
          - href: stories/exampleStory.qmd
            text: "A scrollyteller tutorial example"
          - href: stories/ECharts.qmd
            text: "An Echarts example"
          - href: stories/ecoAssetsDataStory.qmd
            text: "EcoAssets story"
  back-to-top-navigation: false
  
format:
  html:
    theme: 
      - lumen
      - styles/theme.scss
    mainfont: DM Sans
    monofont: Fira Code
    css: styles/styles.css
    toc: true
    code-overflow: scroll

editor: visual



