project:
  type: website

website:
  title: "EcoAssets"
  navbar:
    background: "#EBFEE7"
    foreground: "#000000"
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - href: about.qmd
        text: About
      - text: "Data"
        menu: 
          - biodiversity_data.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

