project:
  type: website

website:
  title: "EcoAssets"
  open-graph: true 
  page-footer: 
    right: "Copyright 2024"
    background: "#EBFEE7"
    foreground: "#000000"
  navbar:
    background: "#EBFEE7"
    foreground: "#000000"
    collapse: true
    pinned: true
    back-to-top-navigation: true
    search: true
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
        aria-label: "Homepage"
      - href: about.qmd
        text: "About"
      - text: "Data"
        menu: 
          - data.qmd
          - biodiversity_data.qmd
          - monitoring_data.qmd
      - href: homepage.qmd
        text: "Home"
      - href: news.qmd
        text: "News"
        
format:
  html:
    theme: 
      - lumen
      - styles_ucsb.scss
    mainfont: Spectral
    monofont: Fira Code
    css: styles.css
    toc: true
    code-overflow: scroll

editor: visual



