---
title: "EcoAssets Data Story"
toc: false
format:
  html: 
    page-layout: custom
    sidebar: true
    include-in-header: 
      - ../progressbar.html
      - ../back-to-top.html
    template-partials: ../title-block.html
execute:
  echo: false
---

::::{#section-1 .story-container}
Section 1 

::: {.columns .column-body-outset}

::: {.column width="35%"}

What is EcoAssets?

:::

::: {.column width="10%"}
:::

::: {.column width="55%" style="position:sticky; top:100px; background-color:purple"}

Bubble graph of organisations

::: {style="background-color: #333; color: white; height: 500px; text-align: center; padding: 20px;"}
PLOT 1: Bubble graph of data contribution by ALA, IMOS, TERN
::: {style="height: 50vh;"}
```{ojs}
import { chart4 } from "@clarapt-ws/ecoassets-dataviz-4-zoomable-circle-plot"
chart4

```
:::
:::

:::

:::

----

## Section 2
::: {.columns .column-body-outset}


::: {.column width="40%}
The ALA, IMOS and TERN have been collecting data since ... 
And every year, they collect and publish more and more data...
:::

::: {.column width="10%"}
:::

::: {.column width="50%" style="position:sticky; top:100px; background-color:purple"}

::: {style="background-color: #333; color: white; height: 800px; text-align: center; padding: 20px;"}
PLOT 2: Line graph of counts vs years (biodiversity data)

```{ojs}
import { linegraph } from "@clarapt-ws/experiments-in-scrollytelling-part-2"
linegraph
```
:::

:::

:::

## Section 3

And they have data about ... 

## Section 4
::: {.column-screen style="border-color: #BD369E; background-size: cover; height: 80vh; position: sticky; top: 0; "}

#### Biodiversity data

## Sum of Occurrence Counts by Australian States and Territories as proportion of total count for 2022 
From EcoAssets Biodiversity aggregate data set

```{ojs}
import { viewof type } from "@clarapt-ws/ecoassets-dataviz-6-shape-tweening"
shape_chart
import { chart as shape_chart } from "@clarapt-ws/ecoassets-dataviz-6-shape-tweening"
shape_chart
```

:::


## Section 5

::: {.grid style="--bs-rows: 3; --bs-columns: 3;"}

::: {}
Auto-column
:::

:::{.g-start-2 style="grid-row: 2"}
#### Monitoring Data

# Counts of monitoring events for EcoAssets data providers, log scaled 

```{ojs}
// import { chart3 } from "@clarapt-ws/ecoassets-dataviz-3-counts-of-monitoring-events-for-ecoass";

myData = [{ id: "flare.ALA.ALA", value: scale(120373)}, {id: "flare.IMOS.IMOS", value: scale(737672)}, {id: "flare.TERN.TERN", value: scale(8971)}]

scale = d3.scaleLog().domain([8971, 737672]).range([0, 100]).nice()

chart3 = {
  // Specify the dimensions of the chart.
  const width = 928;
  const height = width;
  const margin = 1; // to avoid clipping the root circle stroke
  const name = d => d.id.split(".").pop(); // "Strings" of "flare.util.Strings"
  const group = d => d.id.split(".")[1]; // "util" of "flare.util.Strings"
  const names = d => name(d).split(/(?=[A-Z][a-z])|\s+/g); // ["Legend", "Item"] of "flare.vis.legend.LegendItems"

  // Specify the number format for values.
  const format = d3.format(",d");

  // Definiendo tus propios colores
const color = d3.scaleOrdinal()
  .range(["#FF7000", "#00ABFF", "#0AC42E"]);

  // Create the pack layout.
  const pack = d3.pack()
      .size([width - margin * 2, height - margin * 2])
      .padding(3);

  // Compute the hierarchy from the (flat) data; expose the values
  // for each node; lastly apply the pack layout.
  const root = pack(d3.hierarchy({children: myData})
      .sum(d => d.value));

  // Create the SVG container.
  const svg = d3.create("svg")
      .attr("width", width)
      .attr("height", height)
      .attr("viewBox", [-margin, -margin, width, height])
      .attr("style", "max-width: 100%; height: auto; font: 20px sans-serif;")
      .attr("text-anchor", "middle");

  // Place each (leaf) node according to the layout’s x and y values.
  const node = svg.append("g")
    .selectAll()
    .data(root.leaves())
    .join("g")
      .attr("transform", d => `translate(${d.x},${d.y})`);

  // Add a title.
  node.append("title")
      .text(d => `${d.data.id}\n${format(d.value)}`);

  // Add a filled circle.
  node.append("circle")
      .attr("fill-opacity", 0.8)
      .attr("fill", d => color(group(d.data)))
      .attr("r", d => d.r);

  // Add a label.
  const text = node.append("text")
      .attr("clip-path", d => `circle(${d.r})`);

  // Add a tspan for each CamelCase-separated word.
  text.selectAll()
    .data(d => names(d.data))
    .join("tspan")
      .attr("x", 0)
      .attr("y", (d, i, nodes) => `${i - nodes.length / 2 + 0.35}em`)
      .text(d => d);

  // Add a tspan for the node’s value.
  text.append("tspan")
    .attr("x", 0)
    .attr("y", d => `${names(d.data).length / 2 + 0.35}em`)
    .attr("fill-opacity", 0.7)
    .text(d => `${format(d.value)}`);

  return Object.assign(svg.node(), {scales: {color}});
}


```

:::

::: {.g-start-3 style="grid-row: 3"}
Auto-column
:::

:::



## Section 6

The aggregated datasets have been used for environmental reporting 

[Plot from Shandiya's presentation]

## Section 7

And also for more interesting things...

# Plot 1: Circles

```{ojs}
import { chart as circle_plot} from "@clarapt-ws/ecoassets-dataviz-1-what-regions-are-species-located-in";
circle_plot
```

# Plot 2: Streamgraph 

```{ojs}
import { chart5_7 } from "@clarapt-ws/ecoassets-dataviz-5-streamgraph";
chart5_7;

```
